### PR TITLE
Major overhaul to the backend and frontend

### PR DESCRIPTION
**Pull request by ScruffyRules**
Image of what it looks like
A very needed thank you to @Cldfire for making the background graphic. <333

### CODE REVIEW

**Comment by Cldfire** [comment]
:+1:

**Comment by Adriani6** [comment]
Nice work.

**Comment by Cldfire** [comment]
@Adriani6 as soon as you update the Chrome Web Store download I'll be putting the link to it in my signature on Spigot :)

**Comment by Adriani6** [comment]
@Cldfire Done. All up and running.

**Comment by Cldfire** [comment]
@Adriani6 signature edited.

**Pull request merged**
